# Generated by Django 2.2.10 on 2020-02-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0005_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
