# Generated by Django 2.2 on 2020-02-16 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration_app', '0005_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_who_uploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookes_uploaded', to='login_registration_app.User')),
                ('users_who_liked', models.ManyToManyField(related_name='books_liked', to='login_registration_app.User')),
            ],
        ),
    ]
