# Generated by Django 2.2 on 2020-02-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
