# Generated by Django 2.2 on 2020-02-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0003_auto_20200215_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
