# Generated by Django 2.2 on 2020-02-15 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_auto_20200215_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses_app.Course'),
        ),
    ]
